feat: setup terraform remote state and automation workflow

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -51,19 +51,61 @@ jobs:
     needs: build-and-push
     runs-on: ubuntu-latest
     steps:
-      - name: Deploy to AWS EC2 via SSH
-        uses: appleboy/ssh-action@master
+      - name: Checkout Code
+        uses: actions/checkout@v4
+
+    #  - name: Deploy to AWS EC2 via SSH
+    #    uses: appleboy/ssh-action@master
+    #    env:
+    #      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}//my-portfolio:latest
+    #    with:
+    #      host: ${{ secrets.HOST }}
+    #      username: ${{ secrets.USERNAME }}
+    #      key: ${{ secrets.SSH_KEY }}
+    #      env: DOCKER_IMAGE_NAME
+    #      script: |
+    #        # sudo docker pull ${{ secrets.DOCKER_HUB_URL }}
+    #        sudo docker pull $DOCKER_IMAGE_NAME
+    #        sudo docker stop my-portfolio || true
+    #        sudo docker rm my-portfolio || true
+    #
+    #        # sudo docker run -d -p 3000:3000 --name my-portfolio ${{ secrets.DOCKER_HUB_URL }}
+    #        sudo docker run -d -p 3000:3000 --name my-portfolio $DOCKER_IMAGE_NAME
+    #
+    #        sudo docker image prune -f
+
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
         with:
-          host: ${{ secrets.HOST }}
-          username: ${{ secrets.USERNAME }}
-          key: ${{ secrets.SSH_KEY }}
-          script: |
-            # sudo docker pull ${{ secrets.DOCKER_HUB_URL }}
-            sudo docker pull tonkung456/my-portfolio:latest
-            sudo docker stop my-portfolio || true
-            sudo docker rm my-portfolio || true
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ap-southeast-1
 
-            # sudo docker run -d -p 3000:3000 --name my-portfolio ${{ secrets.DOCKER_HUB_URL }}
-            sudo docker run -d -p 3000:3000 --name my-portfolio tonkung456/my-portfolio:latest
+      - name: Update Kubeconfig
+        run: aws eks update-kubeconfig --name tonkung-eks-cluster-v2 --region ap-southeast-1
 
-            sudo docker image prune -f
+      - name: Deploy to EKS
+        run: |
+          kubectl apply -f eks-cluster/k8s/deploy.yaml
+          kubectl apply -f eks-cluster/k8s/service.yaml
+          kubectl rollout restart deployment portfolio-deployment
+
+      - name: Debug Secret Check
+        run: |
+          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
+            echo "ERROR: DISCORD_WEBHOOK is empty! Check your Repo Secrets."
+            exit 1
+          else
+            echo "DISCORD_WEBHOOK is set."
+          fi
+
+      - name: Discord Notification
+          uses: sarisia/actions-status-discord@v1
+          if: always()
+          with:
+            webhook: ${{ secrets.DISCORD_WEBHOOK }}
+            status: ${{ job.status }}
+            contant: "The system is reporting the deployment results."
+            title: "Deployment Status"
+            description: "***Project:*** Portfolio Next.js\n***Branch:*** ${{ github.ref_name }}\n***Status:*** ${{ job.status }}"
+            color: ${{ job.status == 'success' && '0x00ff00' || '0xff0000' }}
